# Generated by Django 3.2 on 2022-12-16 12:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='title',
            new_name='title_id',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.title'),
        ),
        migrations.AlterUniqueTogether(
            name='reviews',
            unique_together={('title_id', 'author')},
        ),
    ]
