# Generated by Django 3.2 on 2023-03-04 12:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_uniqueconsReview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, validators=[django.core.validators.MaxValueValidator(2023, 'Год выпуска не может быть больше текущего')], verbose_name='Год произведения'),
        ),
    ]
